server:
  port: 8999

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: trace
    org.springframework.security.jackson2: INFO

spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8999/oauth2/introspect
          client-id: demo-client-opaque
          client-secret: secret

client-id: thirdparty-amm-trasparente